### ISSUE TITLE
Library code licensing

### ISSUE THREAD

**Issue by asiekierka** [BrokeStudio/rainbow-lib#3]
The provided library code for using the Rainbow mapper on NES (`NES/asm6/` and `NES/cc65/`) does not have a license attached. Because copyright is all rights reserved by default, that causes legal concernes for using it directly by projects which intend to make use of the Rainbow mapper.

Is this the intended state of affairs, and if not, what is the license on the code? Personally, I would recommend something like the zlib license - it means binaries do not need to carry a copyright notice, which is tricky to ensure with NES ROMs, and only source code does. For context, cc65's standard library is also licensed under the zlib license.

**Comment by BrokeStudio** [comment]
Thanks for pointing it out. I added license files using the WTFPL license.

**Comment by asiekierka** [comment]
Personally, I'd recommend something that's legally clear but functionally equivalent, like Creative Commons Zero or 0BSD (these are regarded as well-written legally).

**Comment by BrokeStudio** [comment]
Fine, I changed it for CC0 1.0 Universal.

**Comment by asiekierka** [comment]
Thank you very much!
